name: Sync PR to GitLab

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create-mr:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout full repo (fetch PR refs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare Git and fetch PR head (supports forks)
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Try to fetch the PR ref (works for PRs in same repo)
          if git fetch origin "refs/pull/${PR_NUMBER}/head:refs/remotes/origin/pr/${PR_NUMBER}"; then
            echo "Fetched refs/pull/${PR_NUMBER}/head"
            git checkout -b "pr-${PR_NUMBER}" "refs/remotes/origin/pr/${PR_NUMBER}"
          else
            # Fallback: try to fetch head branch from the head repo (works for forks if accessible)
            echo "Fallback: fetching from head repo ${PR_HEAD_REPO}"
            git remote add headrepo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${PR_HEAD_REPO}.git" || true
            git fetch headrepo "${PR_HEAD_REF}:${PR_HEAD_REF}" || git fetch headrepo "${PR_HEAD_SHA}:${PR_HEAD_REF}"
            git checkout -b "pr-${PR_NUMBER}" "${PR_HEAD_REF}"
          fi

      - name: Add GitLab remote and push PR branch
        env:
          GITLAB_REMOTE_URL: ${{ secrets.GITLAB_REMOTE_URL }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          BRANCH="pr-${PR_NUMBER}"
          git remote add gitlab "${GITLAB_REMOTE_URL}" || git remote set-url gitlab "${GITLAB_REMOTE_URL}"
          git push --force-with-lease gitlab "refs/heads/${BRANCH}:refs/heads/${BRANCH}"
          echo "Pushed ${BRANCH} to GitLab"
          echo "PUSHED_BRANCH=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Create MR in GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          PROJECT_ID: 14
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          # Utiliser la branche que l'on a effectivement poussée
          PR_BRANCH="${{ steps.push_gitlab.outputs.PUSHED_BRANCH }}" || PR_BRANCH="pr-${{ github.event.number }}"
          curl --request POST \
            --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
            --data-urlencode "source_branch=$PR_BRANCH" \
            --data-urlencode "target_branch=main" \
            --data-urlencode "title=[GitHub PR] $PR_TITLE" \
            --data-urlencode "description=PR mirror from GitHub: $PR_URL" \
            "https://gitlab.hoohoo.fr/api/v4/projects/$PROJECT_ID/merge_requests"